// Plantilla verbatim del contrato de arrendamiento (Edificio / Isaias Ariza).
// El "$" se escapa como "\$" para evitar interpolación de template literals; el resto es texto literal.
export default `
CONTRATO DE ARRENDAMIENTO

LUGAR Y FECHA DEL CONTRATO: Santa Marta, {{FECHA_INICIO_DIA_NUM}} DE {{FECHA_INICIO_MES}} DE {{FECHA_INICIO_ANIO}}

ARRENDADOR:	ARRENDADOR: ISAIAS DAVID ARIZA IBARRA
      C.C 1.004.463.223 de Santa Marta.

ARRENDATARIO: {{ARRENDATARIO_NOMBRE}}
	C.C {{ARRENDATARIO_CC}}, {{ARRENDATARIO_CC_LUGAR}}

INMUEBLE: {{INMUEBLE_DIRECCION}}

FECHA DE INICIO: {{FECHA_INICIO_DIA_PALABRAS}} ({{FECHA_INICIO_DIA_NUM}}) De {{FECHA_INICIO_MES}} De {{FECHA_INICIO_ANIO}}

VIGENCIA: {{VIGENCIA_MESES_PALABRAS}} ({{VIGENCIA_MESES_NUM}}) meses

VALOR CANON:                         	a) (\${{VALOR_ARRIENDO_NUM}}), valor del Arrendamiento
                                                            b) (\${{VALOR_DEPOSITO_NUM}}), valor del depósito.

CONDICIONES GENERALES:
En Santa Marta, a los {{FECHA_INICIO_DIA_PALABRAS}} ({{FECHA_INICIO_DIA_NUM}}) Dias del mes de {{FECHA_INICIO_DIA_PALABRAS}} del año {{FECHA_INICIO_ANIO}}, Presentes, a) ISAIAS DAVID ARIZA IBARRA, identificada con la cédula de ciudadanía 1.004.463.223 de Santa Marta, en adelante se denominara como ARRENDADOR  b) Por la otra {{ARRENDATARIO_NOMBRE}}, identificado con cedula de ciudadanía  C.C {{ARRENDATARIO_CC}}, y en adelante se denominará como ARRENDATARIO y que para efectos de nombrar a ambos en el mismo en adelante acá se denominarán como las PARTES, han decidido de común acuerdo suscribir el presente CONTRATO DE ARRENDAMIENTO sobre el inmueble identificado así {{INMUEBLE_DIRECCION}} de la actual nomenclatura urbana de Santa marta D.T.C.H. , para  lo cual acuerden cumplir con las siguientes Cláusulas:

PRIMERA: OBJETO DEL CONTRATO. - Por medio del presente contrato el ARRENDADOR da al ARRENDATARIO a título de arrendamiento y éste a su vez recibe de él al mismo título, los inmuebles: {{INMUEBLE_DIRECCION}} de la ciudad de Santa Marta, Magdalena.  PARAGRAFO: Bienes accesorios.
SEGUNDO: DESTINACION. - El arrendatario se obliga a usar el inmueble para vivienda y no podrá darle otro uso, ni ceder o transferir el contrato de arrendamiento sin la autorización escrita del arrendador. El incumplimiento de esta cláusula dará derecho al arrendador para dar por terminado el contrato y exigir la entrega del inmueble y de los bienes muebles. PARAGRAFO PRIMERO: EL ARRENDATARIO responderá por todas las obligaciones contraídas en el presente contrato, así como las que le impone la ley, no solo por el término principal sino durante sus prórrogas tácitas o automáticas y en el evento de renovaciones por escrito pactadas hasta la fecha de restitución del inmueble.

TERCERA:   VALOR   DEL   CANON   DE   ARRENDAMIENTO. -   El   ARRENDATARIO   pagará al ARRENDADOR como canon mensual de arrendamiento, la suma de {{VALOR_ARRIENDO_PALABRAS}} PESOS (\${{VALOR_ARRIENDO_NUM}}). Esta suma será pagada de forma anticipada los días {{FECHA_INICIO_DIA_PALABRAS}} ({{FECHA_INICIO_DIA_NUM}}) de cada período mensual, con un tiempo máximo de 5 días pasada la fecha antes mencionada. PARAGRAFO 1.- El atraso en el pago del canon establecido generará intereses moratorios a la tasa bancaria más alta del mercado, los que serán cancelados al momento de realizar el pago respectivo PARAGRAFO 2: El arrendatario pagara la suma de {{VALOR_DEPOSITO_PALABRAS}} PESOS (\${{VALOR_DEPOSITO_NUM}}), por concepto de garantía del bien inmueble.
CUARTA: VIGENCIA DEL CONTRATO.- El presente contrato tendrá una vigencia de seis (6) meses, contados a partir del día {{FECHA_INICIO_DIA_NUM}} De {{FECHA_INICIO_MES}} Del año {{FECHA_INICIO_ANIO}} fecha de entrega del inmueble, y podrá prorrogarse si las partes así lo acuerdan, mediante documento escrito PARAGRAFO.- Si el Arrendatario no manifiesta al Arrendador por escrito y enviado por correo certificado con una antelación no inferior a un (01) mes, su interés de darlo por terminado, se entenderá prorrogado por un término igual al estipulado.
QUINTA: INCREMENTOS EN EL PRECIO.- Vencido el primer año de vigencia de este contrato, y así sucesivamente cada 12 mensualidades, en caso de prórroga tácita o expresa, en forma automática y sin necesidad de requerimiento alguno entre las partes, el precio mensual del arrendamiento se incrementará en una proporción igual al 100% del incremento que haya tenido el índice de Precios al Consumidor (IPC), publicado por el Departamento Administrativo Nacional de Estadísticas (DANE) para el año calendario inmediatamente anterior, o por la oficina del gobierno nacional que asuma estas funciones si fuere el caso. PARAGRAFO: el ARRENDATARIO autoriza expresamente al ARRENDADOR para adicionar unilateralmente en éste mismo documento el REAJUSTE acordado, sin necesidad de nuevas firmas por parte de los contratantes. Lo mismo el cambio de nomenclatura que se pueda presentar y adicionar linderos de la propiedad, con plena validez para todos los efectos legales.
SEXTA: SERVICIOS. - los servicios de Energía eléctrica, agua y gas, se encuentran incluidos en el canon de arrendamiento, por lo tanto, estarán a cargo y serán pagados directamente por el ARRENDADOR, a partir de la entrada en vigor del contrato. Los servicios públicos adicionales que fuesen instalados correrán por cuenta del ARRENDATARIO. Para todos los efectos, se entenderán que las obligaciones y derechos emanados del contrato de suscripción recaerán sobre el ARRENDATARIO, quien declara liberado al ARRENDADOR de todo tipo de responsabilidad directa o indirectamente relacionada con el (los) mencionado(s) servicio(s) público(s).
SEPTIMA: CLAUSULA PENAL. - El incumplimiento por parte de cualquiera de las partes de las cláusulas de este contrato, constituirá a la parte incumplida, en deudor de la parte cumplida, de una suma equivalente a tres (3) cánones mensuales de arrendamiento vigentes en el momento en que tal incumplimiento se presente, a título de pena. Se entenderá, en todo caso, que el pago de la pena no extingue la obligación principal y que la parte incumplida podrá pedir a la vez el pago de la pena y la indemnización de perjuicios, si es el caso. Este contrato será prueba sumaria suficiente para el cobro de esta pena y las partes renuncian expresamente a cualquier requerimiento privado judicial para constituirlos en mora del pago de esta o cualquier otra obligación derivada del contrato.
OCTAVA: CAUSALES DE TERMINACION. - A favor del ARRENDADOR serán las siguientes: a) La cesión o subarriendo sin autorización escrita del ARRENDADOR. b) El no pago del precio dentro del término previsto en este contrato. c) La destinación del inmueble para fines ilícitos o contrario a las buenas costumbres, o que representen peligro para el inmueble o la salubridad de sus habitantes. d) Cuando el inmueble haya de demolerse para efectuar una nueva construcción, o cuando se requiere desocupado con el fin de ejecutar obras indispensables para su reparación cumpliendo con el desahucio del Código de Comercio. e) la no cancelación oportunidad de los servicios públicos a cargo del arrendatario. g) Las demás causales previstas en la ley.
NOVENA: OBLIGACIONES DEL ARRENDATARIO. - El ARRENDATARIO está obligado a: 1.- Dar Aviso al ARRENDADOR, sobre daños en el inmueble que pongan en peligro la construcción o el normal funcionamiento de los servicios. 2.- Efectuar en el inmueble, sin derecho a reembolso, las reparaciones locativas derivadas del mal uso del inmueble o de la culpa exclusiva del ARRENDATARIO 3.- Entregar al ARRENDADOR la correspondencia y/o recibos que le entreguen de la Administración o que reciba de las Empresas Distritales o de Servicios Públicos, con destino al propietario y que no le corresponda pagar a él, velando por que su entrega se haga sin dilaciones que impliquen un eventual incumplimiento en las fechas de pago. 4.- Restituir el inmueble en el mismo estado en que fue recibido. 5.- Como al momento de entrega del inmueble por parte del ARRENDATARIO al ARRENDADOR, al momento de la terminación del presente contrato habrá consumos de servicios públicos y otros tales como servicio de televisión digital o cable, alarma, etc., que no hayan sido facturados, pero que son a cargo del  ARRENDATARIO, las partes convienen que en el momento en que el ARRENDATARIO notifique la entrega del inmueble al ARRENDADOR, le hará entrega de una suma de dinero calculada sobre el promedio de los servicios públicos que haya consumido en los últimos tres meses. Esta suma será legalizada por el ARRENDADOR haciendo las devoluciones que correspondan o facturando los saldos faltantes si los hubiere.
DECIMA: CESION. - Ninguna de las partes podrá ceder el presente contrato de arrendamiento sin la autorización previa, expresa y escrita de la otra parte.
DECIMA PRIMERA: RECIBO Y ESTADO. - El ARRENDATARIO declara que ha recibido el inmueble objeto de este contrato en buen estado, y que en el mismo estado lo restituirá al ARRENDADOR a la terminación del arrendamiento, o cuando este haya de cesar por alguna de las causales previstas, salvo el deterioro proveniente del tiempo.
DECIMA SEGUNDA: MEJORAS.- Las reparaciones, variaciones, reformas o mejoras de cualquier clase que quisiere hacer el ARRENDATARIO, serán por cuenta de éste y para efectuarlas se requiere previo permiso o autorización escrita del ARRENDADOR, siendo que en cualquier caso, ellas quedarán de propiedad del dueño del inmueble, sin que el Arrendador quede obligado a pagar tales reformas o mejoras, ni a indemnizar en forma alguna al Arrendatario, aún en los casos en que el Arrendador las haya autorizado expresamente, ni el Arrendatario podrá esperar o llevarse los materiales utilizados. Queda expresamente estipulado que cualquier cerradura o implementos adicionales que el Arrendatario instale en las puertas y ventanas interiores o exteriores del inmueble no las podrá retirar y quedarán de propiedad del Arrendador sin que haya lugar de reconocimiento de suma alguna por este concepto. No obstante, lo dispuesto en esta cláusula, el Arrendatario está obligado a efectuar en el inmueble las reparaciones locativas o sustituciones necesarias a que haya lugar, según lo previsto en el numeral 2 de Art. 9 de la Ley 820 de 2003. La violación de esta cláusula dará derecho al Arrendador para la terminación unilateral del contrato con la consiguiente indemnización de perjuicios a cargo del Arrendatario. En ningún caso tendrá el Arrendatario derecho de retención del inmueble por razón de las mejoras ni derecho a indemnización alguna. PARAGRAFO: según lo referido en el Artículo 27 de la Ley 820 de 2003, en caso de presentarse un daño al inmueble, y se deba realizar una reparación indispensable, el ARRENDATARIO deberá avisar por escrito al ARRENDADOR sobre este daño, y este enviara en la brevedad una persona en su representación para verificar si tal daño, le corresponde al ARRENDADOR o ARRENDATARIO, así mismo, la parte a quien corresponda asumirá dichos costos.
DECIMA TERCERA: GASTOS. - Los derechos, impuestos, tasas y contribuciones que cause la celebración, ejecución, terminación o liquidación del presente contrato serán asumidos por quien la ley designe como responsables.
DÉCIMA CUARTA: REQUERIMIENTOS: El arrendatario y los deudores solidarios que suscriben este contrato renuncian expresamente a los requerimientos de que trata el artículo 2007 del Código Civil y en general a los que consagre cualquier norma sustancial o procesal para efectos de la constitución en mora.
DECIMA QUINTA: ABANDONO DEL INMUEBLE.- Al suscribir este contrato El ARRENDATARIO faculta expresamente al ARRENDADOR para penetrar en el inmueble y recuperar su tenencia, con el solo requisito de la presencia de dos (02) testigos, en procura de evitar el  deterioro o el desmantelamiento de tal inmueble, siempre que por cualquier circunstancia el mismo parezca abandonado o deshabitado por el término de dos (2) meses o más y que la exposición al riesgo sea tal que amenace la integridad física del bien o la seguridad del vecindario.
DÉCIMA SEXTA: PREAVISOS PARA LA ENTREGA. - las partes podrán dar por terminado unilateralmente el contrato de arrendamiento a la fecha de vencimiento del término inicial o de sus prórrogas, siempre y cuando dé previo aviso por escrito a través del servicio postal autorizado, con una antelación no menor a un (1) mes a la referida fecha de vencimiento. La terminación unilateral por parte del arrendatario en cualquier otro momento solo se aceptará previo el pago de una indemnización equivalente al precio de tres (3) meses de arrendamiento que esté vigente en el momento de entrega del inmueble.
DECIMA SEPTIMA: MERITO EJECUTIVO. - El presente contrato presta merito ejecutivo para exigir el pago de la multa estipulada y los cánones que salga a deber el Arrendatario. En cuanto a los cargos del Arrendatario por concepto de servicios públicos domiciliarios o expensas comunes dejadas de pagar, el Arrendador podrá repetir lo pagado contra el Arrendatario por labia ejecutiva mediante la presentación de facturas, comprobantes o recibos de las correspondientes empresas debidamente canceladas y la manifestación que haga el demandante bajo la gravedad de juramento que dichas facturas fueron canceladas por él.
DECIMA OCTAVA: EXENCION DE RESPONSABILIDAD. -    El ARRENDADOR no asume responsabilidad alguna por los daños o perjuicios que el ARRENDATARIO pueda sufrir por causas atribuibles a terceros arrendatarios o de sus empleados o dependientes ni por hurtos o siniestros causados por incendio, inundación o terrorismo.
DECIMA NOVENA: CAMBIOS. - solo serán válidos los cambios al presente contrato, establecidos mediante documentos escritos suscritos por los representantes autorizados de las partes.
VIGECIMA: NOTIFICACIONES. Las notificaciones judiciales y extrajudiciales relacionadas directa o indirectamente con el presente Contrato deberán ser enviadas a las siguientes direcciones, vía correo certificado:
[[TABLA]]
ARRENDADOR:
ISAIAS DAVID ARIZA IBARRA
Kra 21a3 #29k 45 Barrio los laureles, Santa Marta, Magdalena
Tel: 304 3856419
Email: alekerooftop@gmail.com
|
ARRENDATARIO:
{{ARRENDATARIO_NOMBRE}}
{{INMUEBLE_DIRECCION}}, Santa Marta, Magdalena
Tel: {{INQUILINO_TELEFONO}}
Email: {{INQUILINO_EMAIL}}
[[FIN_TABLA]]

En constancia de lo anterior, se firma en Santa Marta D.T.C.H (Magdalena) dos (2) ejemplares del mismo valor y tenor, con destino a cada una de las partes, a los {{FECHA_INICIO_DIA_PALABRAS}} ({{FECHA_INICIO_DIA_NUM}}) Dias del mes de {{FECHA_INICIO_MES}} del año {{FECHA_INICIO_ANIO}}, así:

[[FIRMAS]]
ARRENDADOR:							ARRENDATARIO:
_________________________				________________________________
ISAIAS DAVID ARIZA IBARRA				           {{ARRENDATARIO_NOMBRE}}
C.C 1.004.463.223                   				            C.C {{ARRENDATARIO_CC}}
[[FIN_FIRMAS]]
`;